// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.knowprocess.rootest.model;

import com.knowprocess.rootest.model.Third;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Third_Roo_Configurable {
    
    declare @type: Third: @Configurable;
    
}
